name: Merge data to master
on:
  push:
    branches:
      - data
jobs:
  mergeToMaster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: data
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master